import {
  LayoutDashboard,
  FlaskConical,
  FileText,
  ShoppingCart,
  CheckSquare,
  Users,
  Beaker,
  KeyRound,
  Boxes,
  PackageOpen,
  BookText,
  Truck,
  BellRing,
  ClipboardList,
  TrendingUp,
  Package,
  BarChart3,
  ShieldAlert,
  type LucideIcon,
} from 'lucide-react';
import type { IconName } from './nav';

export const ICONS: Record<IconName, LucideIcon> = {
  LayoutDashboard,
  FlaskConical,
  FileText,
  ShoppingCart,
  CheckSquare,
  Users,
  Beaker,
  KeyRound,
  Boxes,
  PackageOpen,
  BookText,
  Truck,
  BellRing,
  ClipboardList,
  TrendingUp,
  Package,
  BarChart3,
  ShieldAlert,
};
